B 315995536 pdsl multi
google/polymorphicDSL pull request #97
Opened 2024-01-04 00:17 UTC by YuriiChukhrai

2024-01-08 21:52 UTC, incident-recipient requested changes
Overall looks good. Some minor fixes requested.

2024-01-08 21:52 UTC, incident-recipient commented on src/main/java/com/pdsl/runners/ExecutorHelper.java
We can reduce the cyclomatic complexity by deleting the 'else' clause on line 140 and instead returning early in the if condition above it.

2024-01-08 21:52 UTC, incident-recipient commented on src/main/java/com/pdsl/runners/junit/PdslGherkinJUnit4Runner.java
> +        else {
This else condition is not needed because you're returning in the if clause. Google's readability documentation talks about this, but it doesn't make sense to link to the internal documentation on a public repo.

2024-01-08 21:52 UTC, incident-recipient commented on src/main/java/com/pdsl/runners/junit/PdslGherkinJUnit4Runner.java
> +                ? new DefaultGherkinTestSpecificationFactory.Builder(polymorphicDslPhraseFilter)
Let's remove the dead code while we're here

2024-01-08 21:52 UTC, incident-recipient commented on src/main/java/com/pdsl/runners/junit/PdslStatement.java
> +       * 1) If the size of collection (of Interpreter - Listener or Visitor) is ONE - it means
A user could just provide a single interpreter in the @Interpretor annotation. I don't think we can assume a size of one means that no interpreter annotation was used. However I think your overall logic is correct here. Can we just modify the comment to handle instances where we have  a single interpreter vs manY?

2024-01-08 21:52 UTC, incident-recipient commented on src/main/java/com/pdsl/testcases/SharedTestCase.java
> +     * Listener/Visitor (InterpreterObj) we can take first one.
They will have the same phrases. The listener/visitors will be different.

2024-01-08 21:52 UTC, incident-recipient commented on src/test/java/com/pdsl/api/GherkinPolymorphicDslTestExecutor.java
> +        MetadataTestRunResults results = gherkinTestExecutor.runTestsWithMetadata(List.of(sharedTestCase), "Interpreter");
The context here should be "component", "API" or whatever tier of the test pyramid you're using.

2024-01-10 21:48 UTC, YuriiChukhrai commented on src/main/java/com/pdsl/runners/ExecutorHelper.java
Done.

2024-01-10 21:49 UTC, YuriiChukhrai commented on src/main/java/com/pdsl/runners/junit/PdslGherkinJUnit4Runner.java
> +        else {
Done.

2024-01-10 21:49 UTC, YuriiChukhrai commented on src/main/java/com/pdsl/runners/junit/PdslGherkinJUnit4Runner.java
> +                ? new DefaultGherkinTestSpecificationFactory.Builder(polymorphicDslPhraseFilter)
Done

2024-01-10 22:03 UTC, YuriiChukhrai commented on src/main/java/com/pdsl/runners/junit/PdslStatement.java
> +       * 1) If the size of collection (of Interpreter - Listener or Visitor) is ONE - it means
1) So it's because we use this definition in the code
```
Interpreter[] interpreters() default {};
```
the size will be `1` even if the user did not provide any interpreters - in that case the `com.pdsl.runners.junit.PdslStatement#sharedTestCase` will have the size 1 and we will use the `MetadataTestRunResults runTestsWithMetadata(Collection<TestCase> testCases, ParseTreeListener grammarListener, String context);`

In the opposite case wwe will use `MetadataTestRunResults runTestsWithMetadata(Collection<SharedTestCase> sharedTestCase, String context);`

2024-01-10 22:05 UTC, YuriiChukhrai commented on src/main/java/com/pdsl/runners/junit/PdslStatement.java
> +       * 1) If the size of collection (of Interpreter - Listener or Visitor) is ONE - it means
Comment was updated.

2024-01-10 22:17 UTC, YuriiChukhrai commented on src/main/java/com/pdsl/testcases/SharedTestCase.java
> +     * Listener/Visitor (InterpreterObj) we can take first one.
Done.

2024-01-10 22:25 UTC, YuriiChukhrai commented on src/test/java/com/pdsl/api/GherkinPolymorphicDslTestExecutor.java
> +        MetadataTestRunResults results = gherkinTestExecutor.runTestsWithMetadata(List.of(sharedTestCase), "Interpreter");
Done.

2024-03-06 23:01 UTC, incident-recipient approved these changes

2024-03-06 23:01 UTC, merged